services:
  postgress:
    image: mysql:8.0.41
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=qa_shop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass